import Link from 'next/link'
import React from 'react'
export default function _error() {
  return (
    <>
    <Head>
        <title>login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='error'>
        <h1>Oups...</h1>
        <h2>Page not found...</h2>
        <Link className='returnLink' href='mainPage'>Return to main page</Link>
    </div>
    </>
    
  )
}
