import Head from 'next/head'
import Layout from '@/component/layout'
import Caroussel from '@/component/caroussel/caroussel'
import BuySection from '@/component/buySection/buySection'

export async function getStaticProps() {
  const allJsonData = await fetch('https://example-data.draftbit.com/books')
    .then(r => r.json())
  return {
    props: {
      allJsonData
    },
  };
}

export default function mainPage({allJsonData}) {
    console.log(allJsonData);
  
    return (
        <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout main={true}>
        <Caroussel/>
        <BuySection/>
        <section>
        <ul>
            {allJsonData.map(p =>{
              return <li>{p.title}</li>
            })}
        </ul>
        </section>
      </Layout>
    </>
    )
}