import Head from 'next/head'
import Layout from '@/component/layout'
import Caroussel from '@/component/caroussel/caroussel'

export default function mainPage() {
    return (
        <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout main={true}>
        <Caroussel/>
      </Layout>
    </>
    )
}